AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: toItem for API

Parameters:
  ServiceName:
    Type: String
    Default: toItem
  Environment:
    Type: String
    Default: Stg
  SendGridApiKey:
    Type: String
    NoEcho: true
  ToEmail:
    Type: String
    NoEcho: true
  AllowOrigin:
    Type: String
    NoEcho: true

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  ServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${ServiceName}-${Environment}-api
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'POST'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: !Sub "'${AllowOrigin}'"

  Message:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-${Environment}-message
      CodeUri: message
      Handler: app.sendMessage
      Runtime: nodejs12.x
      Environment:
        Variables:
          SENDGRID_API_KEY: !Ref SendGridApiKey
          TO_EMAIL: !Ref ToEmail
          ALLOW_ORIGIN: !Ref AllowOrigin
      Events:
        MessageEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApi
            Path: /message
            Method: POST

Outputs:
  MessageArn:
    Value: !GetAtt Message.Arn
