AWSTemplateFormatVersion: 2010-09-09
Description: Custom domain for API Gateway.

Parameters:
  ServiceName:
    Type: String
    Default: toitem
  NakedDomainName:
    Type: String
    NoEcho: true
  CFSSLCertificateId:
    Type: String
    NoEcho: true
  ApiGatewayProdId:
    Type: String
    NoEcho: true
  ApiGatewayDevId:
    Type: String
    NoEcho: true

Resources:
  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub api.${NakedDomainName}
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Sub arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${CFSSLCertificateId}

  BasePathMappingProd:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      RestApiId: !Ref ApiGatewayProdId
      DomainName: !Ref DomainName
      Stage: prod
      BasePath: prod

  BasePathMappingDev:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      RestApiId: !Ref ApiGatewayDevId
      DomainName: !Ref DomainName
      Stage: dev
      BasePath: dev
