AWSTemplateFormatVersion: 2010-09-09
Description: ToItem for s3 hosting with CloudFront(OAI).

Parameters:
  ServiceName:
    Type: String
    NoEcho: true
  TemplateBucketName:
    Type: String
    NoEcho: true
  HostingBucketName:
    Type: String
    NoEcho: true
  NakedDomainName:
    Type: String
    NoEcho: true
  CFSSLCertificateId:
    Type: String
    NoEcho: true

Resources:
  OaiHostingProd:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucketName}/oai_hosting/oai_hosting.yml
      Parameters:
        ServiceName: !Ref ServiceName
        DomainName: !Sub www.${NakedDomainName}
        HostingBucketName: !Ref HostingBucketName
        CFSSLCertificateId: !Ref CFSSLCertificateId
