AWSTemplateFormatVersion: 2010-09-09
Description: S3 static hosting with CloudFront(OAI).

Parameters:
  ServiceName:
    Type: String
    Default: toitem
  Environment:
    Type: String
    Default: stg
  NakedDomainName:
    Type: String
    NoEcho: true
  SubDomainName:
    Type: String
    NoEcho: true
  HostingBucketName:
    Type: String
    NoEcho: true
  CFSSLCertificateId:
    Type: String
    NoEcho: true

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref HostingBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: true

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${Bucket}/*
              - !Sub arn:aws:s3:::${Bucket}
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub access-identity-${Bucket}

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_All
        Aliases:
          - !Sub ${SubDomainName}.${NakedDomainName}
        Origins:
          - DomainName: !GetAtt Bucket.DomainName
            Id: !Sub S3origin-${HostingBucketName}
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !Sub S3origin-${HostingBucketName}
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          MinTTL: 0
          MaxTTL: 31536000
          DefaultTTL: 86400
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2019
          AcmCertificateArn: !Sub arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${CFSSLCertificateId}
        HttpVersion: http2
        Enabled: true

Outputs:
  BucketId:
    Value: !Ref Bucket
  BucketDomainName:
    Value: !GetAtt Bucket.DomainName
  CloudFrontOriginAccessIdentityId:
    Value: !Ref CloudFrontOriginAccessIdentity
  CloudFrontDistributionID:
    Value: !Ref CloudFrontDistribution
  CloudFrontDistributionDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
