name: API Gateway

on:
  pull_request:
    branches:
      - master
      - develop
    types: [closed]
    paths:
      - 'api-gateway/**'
      - '!api-gateway/.events/**'
      - '!api-gateway/.gitignore'
      - '!api-gateway/README.md'
  workflow_dispatch:

env:
  ENVIRONMENT: ${{
    (github.base_ref == 'master' && 'prod') ||
    (github.base_ref == 'develop' && 'dev') ||
    'dev' }}
  ALLOW_ORIGIN: ${{
    (github.base_ref == 'master' && 'https://www.toitem.info') ||
    (github.base_ref == 'develop' && '*') ||
    '*' }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install SAM
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli

      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Test message
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          ALLOW_ORIGIN: $ALLOW_ORIGIN
        run: |
          cd api-gateway/message
          npm install
          npm run test

      - name: Build by SAM
        run: |
          cd api-gateway
          sam build

      - name: Packaging by SAM
        run: |
          cd api-gateway
          sam package \
            --template-file template.yml \
            --s3-bucket ${{ secrets.TEMPLATE_BUCKET_NAME }} \
            --s3-prefix api-gateway-$ENVIRONMENT \
            --output-template-file deploy.yml

      - name: Deploy by SAM
        run: |
          cd api-gateway
          sam deploy \
            --template-file deploy.yml \
            --stack-name toitem-api-$ENVIRONMENT \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
                Environment=$ENVIRONMENT \
                SendGridApiKey=${{ secrets.SENDGRID_API_KEY }} \
                ToEmail=${{ secrets.TO_EMAIL }} \
                AllowOrigin=$ALLOW_ORIGIN
