name: Custom Domain

on:
  pull_request:
    branches:
      - master
    types: [closed]
    paths: 'cfn/custom-domain/**'
  workflow_dispatch:

env:
  NAKED_DOMAIN_NAME: toitem.info

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy Stack
        run: |
          cd cfn/custom-domain
          aws cloudformation deploy \
            --stack-name toitem-custom-domain \
            --template-file main.yml \
            --s3-bucket ${{ secrets.TEMPLATE_BUCKET_NAME }} \
            --s3-prefix custom-domain \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              NakedDomainName=$NAKED_DOMAIN_NAME \
              CFSSLCertificateId=${{ secrets.CFSSL_CERTIFICATE_TOKYO_ID }} \
              ApiGatewayProdId=${{ secrets.APIGW_PROD_ID }} \
              ApiGatewayDevId=${{ secrets.APIGW_DEV_ID }}
