name: Lambda@Edge

on:
  pull_request:
    branches:
      - master
    types: [closed]
    paths:
      - 'lambda@edge/**'
      - '!lambda@edge/.events/**'
      - '!lambda@edge/.gitignore'
      - '!lambda@edge/README.md'

env:
  ALLOW_ORIGIN: ${{ 
    (github.base_ref == 'master' && 'https://www.toitem.info')  || 
    (github.base_ref == 'staging' && 'https://stg.toitem.info') || 
    '*' }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install SAM
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli

      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Test basic-auth
        run: |
          cd lambda@edge/basic-auth
          cat << EOF >> .env
          AUTH_USER=${{ secrets.BASIC_AUTH_USER }}
          AUTH_PASS=${{ secrets.BASIC_AUTH_PASS }}
          EOF
          npm install
          npm run test
          rm -rf node_modules __test__
          npm install --production

      - name: Test cloudfront-redirect-rootobjects
        run: |
          cd lambda@edge/cloudfront-redirect-rootobjects
          npm install
          npm run test
          rm -rf node_modules __test__

      - name: Build by SAM
        run: |
          cd lambda@edge
          sam build

      - name: Packaging by SAM
        run: |
          cd lambda@edge
          sam package \
            --template-file template.yml \
            --s3-bucket ${{ secrets.TEMPLATE_BUCKET_NAME }}-virginia \
            --s3-prefix lambda-edge \
            --output-template-file deploy.yml \
            --region us-east-1

      - name: Deploy by SAM
        run: |
          cd lambda@edge
          sam deploy \
            --template-file deploy.yml \
            --stack-name toitem-lambda-edge \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1
