name: Deployment for oai static hosting

on:
  pull_request:
    branches:
      - master
      - staging
    types: [closed]
    paths: 'cfn/oai_hosting/**'

env:
  NAKED_DOMAIN_NAME: toitem.info
  SUB_DOMAIN_NAME: ${{ (github.base_ref == 'master' && 'www') || (github.base_ref == 'staging' && 'stg') || 'stg' }}
  ENVIRONMENT: ${{ (github.base_ref == 'master' && 'prod') || (github.base_ref == 'staging' && 'stg') || 'stg' }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy Stack
        run: |
          cd cfn/oai_hosting
          aws cloudformation deploy \
            --stack-name toitem-oai-static-hosting-$ENVIRONMENT \
            --template-file main.yml \
            --s3-bucket ${{ secrets.TEMPLATE_BUCKET_NAME }} \
            --s3-prefix oai-hosting-$ENVIRONMENT \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              Environment=$ENVIRONMENT \
              NakedDomainName=$NAKED_DOMAIN_NAME \
              SubDomainName=$SUB_DOMAIN_NAME \
              HostingBucketName=${{ secrets.HOSTING_BUCKET_NAME }}-$ENVIRONMENT \
              CFSSLCertificateId=${{ secrets.CFSSL_CERTIFICATE_VIRGINIA_ID }}
